version: '{build}'
clone_folder: c:\projects\caffe2
environment:
  matrix:
    - USE_CUDA: OFF
      CMAKE_BUILD_TYPE: Release
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    # Building CUDA with Visual Studio 2017 is yet to be supported by
    # NVidia, so we canot enable it right now.
    #- USE_CUDA: ON
    #  CMAKE_BUILD_TYPE: Release
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - USE_CUDA: ON
      CMAKE_BUILD_TYPE: Release
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    - USE_CUDA: OFF
      CMAKE_BUILD_TYPE: Release
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    # Debug build is not a top priority for us right now, so in the
    # interest of contbuild time, we disable it.
    #- USE_CUDA: OFF
    #  CMAKE_BUILD_TYPE: Debug
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    # Currently, CUDA + Debug does not work due to a error of using
    # std::_Debug_lt in device code. Not sure where this comes from yet,
    # but it is probably safe to assume that very few are going to build
    # debug mode with CUDA and Windows.
    #- USE_CUDA: ON
    #  CMAKE_BUILD_TYPE: Debug

install:
- cmd: c:\projects\caffe2\scripts\appveyor\install.bat

build_script:
- cmd: >-
    cd c:\projects\caffe2

    git submodule update --init

    call scripts\build_windows.bat
